### PR TITLE
Fixing Issue with Orphaned Agents and configurable startup timeout (#1)

### PR DESCRIPTION
**Pull request by aphill70**
Adding Configurable Agent Startup Timeout for workers. This was simply an addition to the Jelly file and a variable in NomadCloud

Fixed a bug that resulted in Agents being orphaned on the Jenkins UI. I debated between throwing the exception or just returning null from the provision call. I ended feeling like the Exception was correct however more than happy to put a null return if that is the more correct way.

Not sure how to exclude the cirlcleci from my fork. If i need to i can remove it

### CODE REVIEW

**Comment by jovandeginste** [comment]
@aphill70 you could add the filename to `.gitignore`?

**Comment by aphill70** [comment]
@jovandeginste I assume you are referring to the circleci file? I have removed it if so

**Comment by jovandeginste** [comment]
@aphill70 yes, sorry for being unclear ...

**Comment by lmasaya** [comment]
We could definitely use this change. I'm trying to launch a slave across AWS regions and 1 minute timeout is terminating slave before it actually gets to run

**Comment by aphill70** [comment]
I will see if i can fix the conflicts tomorrow didn't realize it had drifted

**Comment by aphill70** [comment]
@lmasaya Sorry this took a bit longer but I think I got everything working again

**Comment by peimanja** [comment]
@aphill70 Thanks a lot! You're a lifesaver. Are you able to look at #47 as well? It prevented us from enabling ACL on our Nomad cluster which is one of the requirements.

**Comment by aphill70** [comment]
Yeah if I get some time I can poke

**Pull request merged**
