### PR TITLE
Nomad 0.5 fix

### PR DESCRIPTION
**Pull request by pawbur**
Support for nomad 0.5 based on @far-blue work in https://github.com/jenkinsci/nomad-plugin/pull/13

I've done some simple tests and seems to work with Docker and Java drivers. Doesn't provide any new features available in 0.5. Breaks compatibility with nomad 0.4.x.

### CODE REVIEW

**Comment by far-blue** [comment]
Win :) Now we just need someone to merge it...

**Comment by iverberk** [comment]
@far-blue @pawbur many thanks for picking this up! I'll do a quick test asap and create a release.

**Comment by antweiss** [comment]
@pawbur @far-blue thanks for this. will also test this as soon as I get to it.

**Comment by pawbur** [comment]
Hi, @iverberk @antweiss
Have you had any time to look at this ?

**Comment by antweiss** [comment]
hi @pawbur, I've built and installed it on our Jenkins  - the slaves get started but then die before connecting back to Jenkins... could be realted to the upgrade and reconfiguration of the Nomad cluster. I'm investigating this but can't really confirm this works for me yet. Will update ASAP.

**Comment by antweiss** [comment]
@pawbur once I changed slave.jar path to /local/slave.jar  for docker driver (docker only!)  - it all works great.
please test your configuration with this and if all is good - we can merge.

**Comment by pawbur** [comment]
@antweiss I changed all slave.jar paths to be absolute /local/slave.jar and it seems to be working for me for docker and java drivers.

**Comment by antweiss** [comment]
@pawbur great! works for me too. merging this into master. 
@iverberk do you have time to release, or should I do it?

**Comment by iverberk** [comment]
@antweiss please go ahead and release it. I'm also adding another maintainer to the project as I have little time/motivation to maintain it without actually using it myself. Thanks for picking this up.

**Comment by antweiss** [comment]
@iverberk and @pawbur thanks a lot! released 0.4

**Comment by far-blue** [comment]
works for me - thanks everyone :)

**Comment by antweiss** [comment]
@far-blue and thank you of course!!! :)

**Pull request merged**
