### PR TITLE
Best effort validation of user input

### PR DESCRIPTION
**Pull request by zstyblik**
PR adds best effort validation of user input. Fall back to sane defaults in case of invalid input.

Fixes https://github.com/jenkinsci/nomad-plugin/issues/22

### CODE REVIEW

**Comment by zstyblik** [comment]
First of all and as before, I'm no Java programmer. Second, I haven't found a better way to validate user input than to do it this way, resp. via `checkUrl` call or whatever it is. There is a drawback, though. Yes, message pops up and warns the user, ***but*** it doesn't prevent user from submitting invalid input. That's where third thing comes in - defaults. I think it's better than to throw an exception. Though, I perceived the code to be ugly.

@jovandeginste, please, can you give this a look?

**Comment by zstyblik** [comment]
I have refactored the code a bit and added unit tests. Unfortunately, I have no idea how to write unit tests for form validation part.

**Comment by zstyblik** [comment]
... or @jippi ?

**Comment by jovandeginste** [comment]
@zstyblik Due to personal stuff, I'm taking some slow weeks.

As a default, I would rather have the code throw errors than do something I didn't expect it to do.

**Comment by zstyblik** [comment]
@jovandeginste sure, no problem.

> As a default, I would rather have the code throw errors than do something I didn't expect it to do.

I'm open to suggestions. However, Java exception says pretty much nothing to the user like any exception from any programming language and code you're not familiar with. In other words, I really hate when Jenkins goes exception on me for no obvious reason.
Anyway, give this patch a try and you will see. Also, as I've stated above, I haven't found way how to prevent form being submitted.

**Comment by phedoreanu** [comment]
@zstyblik Would you please rebase and add the security fixes from #42 ?

**Pull request closed without merging**
